
export enum PlumbingEnum{
	TAP = <any>"TAP",
	WASH_BASIN = <any>"WASH BASIN",
	KITCHEN_SINK = <any>"KITCHEN SINK",
	WESTERN_TOILET = <any>"WESTERN TOILET",
	FLUSH_TANK = <any>"FLUSH TANK",
	INDIAN_TOILET = <any>"INDIAN TOILET",
	TOILET_JET = <any>"TOILET JET",
	SHOWER = <any>"SHOWER",
	PIPELINE = <any>"PIPELINE",
	PUMPS = <any>"PUMPS",
	OTHERS = <any>"OTHERS",
}

export enum ElectricalEnum{
	CEILING_FAN = <any>"CEILING FAN",
	EXHAUST_FAN = <any>"EXHAUST FAN",
	STAND_FAN = <any>"STAND FAN",
	MCB = <any>"MAIN CONTROL BOARD",
	NEW_ELECTRIC_POINT = <any>"NEW ELECTRIC POINT",
	THREE_PHASE_PANNEL_BOARD = <any>"THREE PHASE PANNEL BOARD",
	WIRING = <any> "WIRING",
	TUBE_LIGHT_WITH_PANNEL = <any>"TUBE LIGHT WITH PANNEL",
	FANCY_LIGHT = <any>"FANCY LIGHT",
	SOCKET_AND_HOLDERS = <any>"SOCKETS AND HOLDERS",
	INVERTER = <any>"INVERTER",
	OTHERS = <any>"OTHERS",
}

export enum CarpentryEnum{
	DOOR_STOPPER = <any>"DOOR STOPPER",
	HANDLE = <any>"HANDLE",
	DOOR_CHAIN = <any> "DOOR CHAIN",
	DOOR_LATCH = <any> "DOOR LATCH",
	HINGES = <any> "HINGES",
	DOOR_PEEPHOLE = <any>"DOOR PEEPHOLE",
	LOCK = <any>"LOCK",
	LAMINATION = <any>"LAMINATION",
	WOODEN_PARTITION = <any>"WOODEN PARTITION",
	MESH = <any>"MESH",
	SOFA = <any>"SOFA",
	WOODEN_CHAIR = <any>"WOODEN_CHAIR",
	BED = <any>"BED",
	FURNITURE_REPAIR = <any> "FURNITURE REPAIR",
	OTHERS = <any>"OTHERS"
}




